services:
  backend:
    container_name: iot-backend
    build: ./backend/room_reservation_system/
    ports:
      - "8000:8000"
    volumes:
      - database:/home/app/webapp/data
  frontend:
    container_name: iot-frontend
    build: ./frontend/
    ports:
      - "3000:3000"
  broker:
    container_name: iot-broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./.broker_config/:/mosquitto/config:rw
      - broker-data:/mosquitto/data:rw
      - broker-log:/mosquitto/log:rw
    user: "1000:1002"
  broker-test-client:
    container_name: iot-broker-test-client
    image: eclipse-mosquitto
volumes:
  broker-log:
  broker-data:
  database:

networks:
  default:
