services:
  backend:
    container_name: backend
    build: ./backend/room_reservation_system/
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "3000:80"

networks:
  default:
